### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by lynn0909** [msracver/Relation-Networks-for-Object-Detection#33]
/home/dlc/anaconda3/envs/torch3_py27/bin/python2.7 /home/dlc/sll/Relation-Networks-for-Object-Detection-master/experiments/relation_rcnn/rcnn_end2end_train_test.py --cfg experiments/relation_rcnn/cfgs/resnet_v1_101_coco_trainvalminus_rcnn_fpn_relation_learn_nms_8epoch.yaml
('Called with argument:', Namespace(cfg='experiments/relation_rcnn/cfgs/resnet_v1_101_coco_trainvalminus_rcnn_fpn_relation_learn_nms_8epoch.yaml', frequent=100))
Traceback (most recent call last):
  File "/home/dlc/sll/Relation-Networks-for-Object-Detection-master/experiments/relation_rcnn/rcnn_end2end_train_test.py", line 21, in <module>
    train_end2end.main()
  File "/home/dlc/sll/Relation-Networks-for-Object-Detection-master/experiments/relation_rcnn/../../relation_rcnn/train_end2end.py", line 184, in main
    config.TRAIN.model_prefix,config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "/home/dlc/sll/Relation-Networks-for-Object-Detection-master/experiments/relation_rcnn/../../relation_rcnn/train_end2end.py", line 66, in train_net
    sym = sym_instance.get_symbol(config, is_train=True)
  File "/home/dlc/sll/Relation-Networks-for-Object-Detection-master/experiments/relation_rcnn/../../relation_rcnn/../lib/utils/symbol.py", line 25, in get_symbol
    raise NotImplementedError()
NotImplementedError
跪求解决方法呜呜~~

**Comment by yanliv** [comment]
请问解决了吗？我遇到了同样的问题
